0.0.8

diff --git a/ginit b/ginit
--- a/ginit
+++ b/ginit
@@ -1,9 +1,6 @@
 #!/bin/env bash
 
 
-source bashlib_y
-
-
 crep(){
 	git add README.md
 	git commit -a -m "0"
@@ -12,7 +9,7 @@ crep(){
 	git remote add origin git@github.com:$G_USER/$target.git
 	git push -u origin main 2>&1| while read ln;do
 		if [ "$ln" = "ERROR: Repository not found." ];then
-			die "Remote repository not found. \nPlease make the repository, '$target' and reexececute 'git push -u origin main' manually"
+			echo "ERROR: Remote repository not found. \nPlease make the repository, '$target' and reexececute 'git push -u origin main' manually" >&2
 		fi
 	done
 }
@@ -21,7 +18,7 @@ crep(){
 if [ -z "$1" ];then
 	PWD="`pwd`"
 	if [ "${PWD%/*}" != $HOME/git_project ];then
-		die "Current direcotry is not an entry in \$HOME/git_project."
+		echo "ERROR: Current direcotry is not an entry in \$HOME/git_project." >&2
 	fi
 	target=${PWD##*/}
 else
@@ -30,12 +27,12 @@ fi
 
 G_USER=`git config user.name`
 if [ -z "$G_USER" ];then
-	die "Missing user for git. 
+	echo "ERROR: Missing user for git. 
 Please set user by executing 'git user.name --(global|local) USER_NAME'"
 fi
 
 if ! [[ $target =~ ^[0-9A-Za-z_]+$ ]];then
-	die "Illeagal name, '$target'"
+	echo "ERROR: Illeagal name, '$target'"
 fi
 
 mkdir -p ~/git_project/$target
